services:
  - type: web
    name: osy-db
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DB_HOST
        value: public-mysql-187728d1-kkonek-2026.l.aivencloud.com
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_SSL_MODE
        sync: false
      - key: DB_SSL_CA
        value: config/ca.pem
      - key: DB_SSL_VERIFY_SERVER_CERT
        value: "false"
      - key: GEMINI_API_KEY
        sync: false
